src/Entity/Batch.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 *
 * @ORM\Entity(repositoryClass="App\Repository\BatchRepository")
 */
class Batch
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="batches")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Server", mappedBy="batch")
     */
    private $servers;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible = true;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Campaign", mappedBy="batch")
     */
    private $campaigns;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ContactList")
     * @ORM\JoinColumn(nullable=false)
     */
    private $contactList;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mode;

    /**
     * @ORM\Column(type="boolean")
     */
    private $setup = false;

    /**
     * @ORM\Column(type="float")
     */
    private $cost = 0;

    /**
     * @ORM\Column(type="float")
     */
    private $revenue = 0;

    public static $modeChoices = [
        "Warmup plan" => "warmup",
        "Send linearly" => "linear",
        "Send simultaneously" => "simultaneous"
    ];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $category;

    public function __construct()
    {
        $this->servers = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->campaigns = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Server[]
     */
    public function getServers(): Collection
    {
        return $this->servers;
    }

    public function addServer(Server $server): self
    {
        if (!$this->servers->contains($server)) {
            $this->servers[] = $server;
            $server->setBatch($this);
        }

        return $this;
    }

    public function removeServer(Server $server): self
    {
        if ($this->servers->contains($server)) {
            $this->servers->removeElement($server);
            // set the owning side to null (unless already changed)
            if ($server->getBatch() === $this) {
                $server->setBatch(null);
            }
        }

        return $this;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * @return Collection|Campaign[]
     */
    public function getCampaigns(): Collection
    {
        return $this->campaigns;
    }

    public function addCampaign(Campaign $campaign): self
    {
        if (!$this->campaigns->contains($campaign)) {
            $this->campaigns[] = $campaign;
            $campaign->setBatch($this);
        }

        return $this;
    }

    public function removeCampaign(Campaign $campaign): self
    {
        if ($this->campaigns->contains($campaign)) {
            $this->campaigns->removeElement($campaign);
            // set the owning side to null (unless already changed)
            if ($campaign->getBatch() === $this) {
                $campaign->setBatch(null);
            }
        }

        return $this;
    }

    public function getContactList(): ?ContactList
    {
        return $this->contactList;
    }

    public function setContactList(?ContactList $contactList): self
    {
        $this->contactList = $contactList;

        return $this;
    }

    public function getMode(): ?string
    {
        return $this->mode;
    }

    public function setMode(string $mode): self
    {
        $this->mode = $mode;

        return $this;
    }

    public function getSetup()
    {
        return $this->setup;
    }

    public function setSetup($setup): void
    {
        $this->setup = $setup;
    }

    public function getCost()
    {
        return $this->cost;
    }

    public function setCost($cost): void
    {
        $this->cost = $cost;
    }

    public function getRevenue()
    {
        return $this->revenue;
    }

    public function setRevenue($revenue): void
    {
        $this->revenue = $revenue;
    }

    public function getAliveCount()
    {
        $count = 0;
        foreach ($this->getServers() as $server) {
            if (!$server->getDead()) {
                $count++;
            }
        }
        return $count;
    }

    public function getDeadCount()
    {
        $count = 0;
        foreach ($this->getServers() as $server) {
            if ($server->getDead()) {
                $count++;
            }
        }
        return $count;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/BatchController.php
<?php

namespace App\Controller;

use App\Entity\Batch;
use App\Entity\Task;
use App\Entity\WarmupPlan;
use App\Form\BatchEditType;
use App\Form\BatchType;
use App\Repository\BatchRepository;
use App\Repository\CategoryRepository;
use App\Repository\ContactListRepository;
use App\Repository\ServerRepository;
use App\Repository\TaskRepository;
use App\Repository\WarmupPlanRepository;
use App\Service\CampaignManager;
use App\Service\ServerManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/batch")
 */
class BatchController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private $em;
    /**
     * @var TaskRepository
     */
    private $taskRepository;
    /**
     * @var ServerRepository
     */
    private $serverRepository;

    public function __construct(EntityManagerInterface $entityManager, TaskRepository $taskRepository, ServerRepository $serverRepository)
    {
        $this->em = $entityManager;
        $this->taskRepository = $taskRepository;
        $this->serverRepository = $serverRepository;
    }

    /**
     * @Route("/", name="batch_index", methods={"GET", "POST"})
     */
    public function index(Request $request, BatchRepository $batchRepository, ContactListRepository $contactListRepository, ServerManager $serverManager, CategoryRepository $categoryRepository)
    {
        $batch = new Batch();
        $form = $this->createForm(BatchType::class, $batch, [
            'contactList_choices' => $contactListRepository->getAccessibleLists($this->getUser()),
            'mode_choices' => Batch::$modeChoices
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $batch->setUser($this->getUser());
            $entityManager->persist($batch);
            $entityManager->flush();

            if (!$serverManager->createServersFromList($batch, $form->get('list')->getData())) {
                $this->addFlash('danger', 'Wrong list of servers.');
                return $this->redirectToRoute('batch_index');
            }

            $this->addFlash('success', 'Batch created successfully!');
            return $this->redirectToRoute('batch_show', ['id' => $batch->getId()]);
        }

        return $this->render('batch/index.html.twig', [
            'form' => $form->createView(),
            'batches' => $batchRepository->getBatchesByUser($this->getUser()),
            'categories' => $categoryRepository->findAll()
        ]);
    }

    /**
     * @Route("/{id}", name="batch_show", methods={"GET"})
     */
    public function show(Batch $batch, ContactListRepository $contactListRepository)
    {
        //If Batch setup process is not finished, User is redirected to batch_setup
        if (!$batch->getSetup()) {
            return $this->redirectToRoute('batch_setup', ['id' => $batch->getId()]);
        }
        $form = $this->createForm(BatchEditType::class, $batch, ['action' => $this->generateUrl('batch_edit', ['id' => $batch->getId()])]);
        return $this->render('batch/show.html.twig', [
            'batch' => $batch,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="batch_edit")
     */
    public function edit(Request $request, Batch $batch)
    {
        $form = $this->createForm(BatchEditType::class, $batch);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Batch edited successfully!');
        }

        return $this->redirectToRoute('batch_show', ["id" => $batch->getId()]);
    }

    /**
     * After creating a new Batch, User enters a second step of the setup.
     * If Batch mode is "warmup", User must choose WarmupPlan
     * If Batch mode is not "warmup", User must specify speed and number of campaigns.
     *
     * After completing this step: Imports, Campaigns (without CampaignContent) and Tasks are created.
     *
     * @Route("/{id}/setup", name="batch_setup", methods={"GET", "POST"})
     */
    public function setup(Request $request, Batch $batch, WarmupPlanRepository $warmupPlanRepository, CampaignManager $campaignManager)
    {
        if ($batch->getMode() == "warmup") {
            $choices = $warmupPlanRepository->getAccessibleWarmupPlans($this->getUser());
            $form = $this->createFormBuilder()
                ->add('warmupPlan', EntityType::class, [
                    'label' => 'Warmup Plan',
                    'class' => WarmupPlan::class,
                    'choices' => $choices,
                    'choice_label' => function (WarmupPlan $warmupPlan) {
                        return $warmupPlan->getName()." (".count($warmupPlan->getPlan())." days)";
                    }
                ])
                ->getForm();
            if (count($choices) == 0) {
                return $this->render('batch/setup_warmup_error.html.twig', [
                    'batch' => $batch,
                ]);
            }
        }
        else {
            $form = $this->createFormBuilder()
                ->add('speed', IntegerType::class, [
                    'label' => 'Hourly quota (0 = no limits)',
                    'attr' => [
                        'min' => 0
                    ]
                ])
                ->add('numberOfCampaigns', IntegerType::class, [
                    'label' => 'Number of campaigns',
                    'attr' => [
                        'min' => 1
                    ]
                ])
                ->getForm();
        }
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($batch->getMode() == "warmup") {
                $campaignManager->createCampaignFromPlan($batch, $form->get('warmupPlan')->getData());
            }
            elseif ($batch->getMode() == "simultaneous") {
                $campaignManager->createCampaign($batch, $form->get('speed')->getData(), $form->get('numberOfCampaigns')->getData());
            }
            else {
                $campaignManager->createCampaign($batch, $form->get('speed')->getData(), $form->get('numberOfCampaigns')->getData());
            }

            $batch->setSetup(true);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('batch_show', ['id' => $batch->getId()]);
        }

        return $this->render('batch/setup.html.twig', [
            'batch' => $batch,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="batch_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Batch $batch)
    {
        if ($this->isCsrfTokenValid('delete'.$batch->getId(), $request->request->get('_token'))) {
            $batch->setVisible(false);

            //kill servers
            foreach ($batch->getServers() as $server) {
                $server->setDead(true);
            }

            $this->em->flush();

            $this->addFlash('success', 'Batch deleted successfully!');
        }

        return $this->redirectToRoute('batch_index');
    }

    /**
     * Clear every server in the batch and make them brand new.
     *
     * @Route("/{id}/clear", name="batch_clear")
     */
    public function clear(Request $request, Batch $batch, ServerManager $serverManager)
    {
        $serverManager->resetServers($batch);
        $batch->setSetup(0);
        $this->getDoctrine()->getManager()->flush();
        $this->addFlash("success", "Batch has been reset successfully.");

        return $this->redirectToRoute('batch_show', ["id" => $batch->getId()]);
    }

    /**
     * Download bounces
     *
     * @Route("/{id}/download/bounces", name="batch_download_bounces")
     */
    public function downloadBounces(Request $request, Task $task, ServerManager $serverManager)
    {
        $bounces = $serverManager->getBounces($task);

        $rows = [];
        $rows[] = implode(',', ["Email", "First Name", "Last Name"]);
        foreach ($bounces as $bounce) {
            $rows[] = implode(',', $bounce);
        }
        $content = implode("\n", $rows);
        $response = new Response($content);
        $response->headers->set('Content-Type', 'text/csv');
        $response->headers->set('Content-Disposition', 'attachment; filename="bounces.csv"');

        return $response;
    }

    /**
     * Download opens
     *
     * @Route("/{id}/download/opens", name="batch_download_opens")
     */
    public function downloadOpens(Request $request, Task $task, ServerManager $serverManager)
    {
        $opens = $serverManager->getOpens($task);

        $rows = [];
        $rows[] = implode(',', ["Email", "First Name", "Last Name"]);
        foreach ($opens as $open) {
            $rows[] = implode(',', $open);
        }
        $content = implode("\n", $rows);
        $response = new Response($content);
        $response->headers->set('Content-Type', 'text/csv');
        $response->headers->set('Content-Disposition', 'attachment; filename="opens.csv"');

        return $response;
    }

    public function findAndRemoveServer(int $id)
    {
        $server = $this->serverRepository->findOneBy(['id' => $id]);

        $server->setCurrentTask(null);
        if (count($server->getTasks()) !== 0) {
            foreach ($server->getTasks() as $task) {
                $task->setServer(null);
                $this->em->remove($task);
                $this->em->flush();

templates/batch/_delete_form.html.twig
<form style="display: inline-block" method="post" action="{{ path('batch_delete', {'id': batch.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ batch.id) }}">
    <button class="btn btn-sm btn-danger batchDeleteButton" id="{{ category }}">Delete</button>
</form>

templates/batch/_form_new.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div id="csv-table"></div>
    <button class="submit btn btn-block btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/batch/_form_setup.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="submit btn btn-block btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/batch/category_table.html.twig
<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Alive / Dead</th>
        <th>Created At</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for batch in batches %}
        {% if batch.category == category %}
            <tr>
                <td>{{ batch.name }}</td>
                <td>{{ batch.description }}</td>
                <td>{{ batch.aliveCount }} / {{ batch.deadCount }}</td>
                <td>{{ batch.createdAt|date('Y-m-d H:i') }}</td>
                <td style="width: 140px">
                    <a href="{{ path('batch_show', {id: batch.id}) }}" class="btn btn-info btn-sm">View</a>
                    {{ include('batch/_delete_form.html.twig') }}
                </td>
            </tr>
        {% endif %}
    {% else %}
        <tr>
            <td colspan="5">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/batch/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Batches{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        td {
            vertical-align: middle !important;
        }
        .category {
            width: 100%;
            background-color: #f7f7f7;
            border: 1px solid rgba(0,0,0,.125);
            cursor: pointer;
        }
        .category-title {
            padding: 10px;
            margin: 0;
            font-size: 20px;
        }

        .category {
            position: relative;
        }

        .category::after {
            content: "\f107";
            color: black;
            top: 20%;
            font-size: 20px;
            right: 25px;
            position: absolute;
            font-family: "FontAwesome"
        }

        .category[aria-expanded="true"]::after {
            content: "\f106";
        }
    </style>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-4">
            <div class="card">
                <div class="card-header">
                    Create new batch
                </div>
                <div class="card-body">
                    {{ include('batch/_form_new.html.twig') }}
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    Batches
                </div>
                <button class="btn btn-primary show-all-batches" style="margin: 10px;" data-toggle="collapse" data-target=".hidden-batch">Toggle Batch visibility</button>
                <div class="card-body">
                    {% set exists = false %}
                    {% for category in categories %}
                        {% for batch in batches %}
                            {% if batch.category == category.title %}
                                {% set exists = true %}
                            {% endif %}
                        {% endfor %}

                        {% if exists == true %}
                            <div class="category" data-toggle="collapse" data-target="#batches-{{ category.title}}">
                                <p class="category-title">{{ category.title }}</p>
                            </div>
                            <div class="hidden-batch collapse" id="batches-{{ category.title}}">
                                {% include 'batch/category_table.html.twig' with {'category': category.title} %}
                            </div>
                        {% endif %}
                        {% set exists = false %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts%}
    {{ parent() }}
    <script>
        let batch = sessionStorage.getItem('batch');

        if (batch) {
            $('#batches-'+ batch).addClass("show");
            sessionStorage.removeItem('batch');
        }

        $('.csv-data-input').on("change input paste keyup", function () {
            var data = $('.csv-data-input').val();
            var rows = data.split("\n");
            var valid = true;

            var table = $('<table class="table table-bordered table-striped" />');

            for(var y in rows) {
                var cells = rows[y].split("\t");
                var row = $('<tr />');
                if ((!ValidateIPaddress(cells[0])) || (cells.length !== 1)) {
                    valid = false;
                }
                for(var x in cells) {
                    row.append('<td>'+cells[x]+'</td>');
                }
                table.append(row);
            }

            if (valid) {
                $('#csv-table').html(table);
                $('.submit').attr("disabled", false);
            }
            else {
                $('#csv-table').html("<div class='alert alert-danger'>Provided data is not valid.</div>");
                $('.submit').attr("disabled", true);
            }
        });

        function ValidateIPaddress(ipaddress) {
            if (/^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test(ipaddress)) {
                return (true)
            }
            return (false)
        }
    </script>

{% endblock %}

templates/batch/servers_card.html.twig
<div class="card">
    <div class="card-header">
        Servers
    </div>
    <div class="card-body">
        {% set deletableServersCard = 0 %}
        {% for server in batch.servers %}
            {% if server.dead == 1 %}
                {% set deletableServersCard = deletableServersCard + 1 %}
            {% endif %}
        {% endfor %}
        <div class="float-right">
            {% if deletableServersCard != 0 %}
                <button id="serverCheckedButton" class="btn btn-danger btn-sm mb-2" disabled>Delete selected servers</button>
            {% endif %}
        </div>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>IP</th>
                <th>Status</th>
                {% if deletableServersCard != 0 %}
                    <th>Delete</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for server in batch.servers %}
                <tr>
                    <td>{{ server.ip }}</td>
                    <td>
                        {% if server.dead != 1 %}
                            {% if server.currentTask is null %}
                                N/A
                            {% elseif server.currentTask.status == 'waiting' and server.currentTask.import.progress >= 0 %}
                                importing ({{ server.currentTask.import.progress }}%)
                            {% elseif server.currentTask.status == 'sending' %}
                                sending ({{ server.currentTask.progress }}%)
                            {% elseif server.currentTask.status == 'sent' %}
                                sent
                            {% endif %}
                        {% else %}
                            DEAD
                        {% endif %}
                    </td>
                    {% if deletableServersCard != 0 %}
                        <td class="text-center">
                            {% if server.dead == 1 %}
                                <input type="checkbox" class="serverDeleteCheck" id="{{ server.id }}">
                            {% endif %}
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/batch/setup.html.twig
{% extends 'base.html.twig' %}

{% block title %}Batch - {{ batch.name }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .form-entry {
            padding: 15px;
            border: 1px solid rgba(0,0,0,.125);
            border-radius: .25rem;
            margin-bottom: 5px;
        }
        .form-entry .form-group {
            margin: 0;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-4">
            {{ include('batch/servers_card.html.twig') }}
        </div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <span>Finish setup</span>
                    <a href="{{ path('batch_index') }}">Go back to Batches</a>
                </div>
                <div class="card-body">
                    {{ include('batch/_form_setup.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/batch/setup_warmup_error.html.twig
{% extends 'base.html.twig' %}

{% block title %}Batch - {{ batch.name }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .form-entry {
            padding: 15px;
            border: 1px solid rgba(0,0,0,.125);
            border-radius: .25rem;
            margin-bottom: 5px;
        }
        .form-entry .form-group {
            margin: 0;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-4">
            {{ include('batch/servers_card.html.twig') }}
        </div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <span>Finish setup</span>
                    <a href="{{ path('batch_index') }}">Go back to Batches</a>
                </div>
                <div class="card-body">
                    <div class="alert alert-danger">No warmup plans available! Please go to <a href="{{ path('warmup_plan_index') }}">Warmup plans</a>.</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}